name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  access-key-id:
    required: true
  secret-access-key:
    required: true
  region:
    required: true
  prject-name:
    required: true
  app-id:
    required: true
  env-name:
    required: true

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'