name: Build & Deploy to Netlify

# https://qiita.com/nwtgck/items/e9a355c2ccb03d8e8eb0

on:
  push:
    paths:
        # frontend ディレクトリとgit直下のファイルが変更された時に実行する
        - 'frontend/**'
        - '*'
        # Workflowが変更された時も実行する
        - '.github/workflows/netlify.yml'

  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract
      id: extract
      run: |
        AMPLIFY_ENV="$(git symbolic-ref --short HEAD)"
        if [ "$AMPLIFY_ENV" = "master" ];then
          AMPLIFY_ENV="prod"
        fi

        echo "##[set-output name=amplify-env;]$AMPLIFY_ENV"

    - name: Echo extracted
      run: echo "${{ steps.extract.outputs.amplify-env }}"

    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Configure Amplify
      uses: ambientlight/amplify-cli-action@0.2.0
      with:
        amplify_command: configure
        amplify_env: amplifyenv
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-1

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: frontend

    # - name: Extract aws-exports.js
    #   run: echo '${{ secrets.AWS_EXPORTS }}' > frontend/src/aws-exports.js

    # - name: Run test
    #   run: yarn test
    #   working-directory: frontend

    - name: Build
      run: yarn build
      working-directory: frontend

    - name: Deploy
      uses: nwtgck/actions-netlify@v1.0
      with:
        publish-dir: frontend/build
        production-branch: master
        github-token: ${{ github.token }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
