name: Build & Deploy to Netlify

# https://qiita.com/nwtgck/items/e9a355c2ccb03d8e8eb0

on:
  push:
    # paths:
        # frontend ディレクトリとgit直下のファイルが変更された時に実行する
        - frontend/**
        - '*'
        # Workflow/actionが変更された時も実行する
        - .github/workflows/netlify.yml
        - .github/actions/configure-amplify/**

  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract
      id: extract
      run: |
        AMPLIFY_ENV="$(git symbolic-ref --short HEAD)"
        if [ "$AMPLIFY_ENV" = "master" ];then
          AMPLIFY_ENV="amplifyenv"
        fi

        echo "##[set-output name=amplify-env;]$AMPLIFY_ENV"

    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install config-amplify action dependencies
      working-directory: .github/actions/configure-amplify
      run: yarn install --frozen-lockfile

    - name: Configure Amplify using action
      uses: ./.github/actions/configure-amplify
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ap-northeast-1
        project-name: aws-amplify-handson
        app-id: ${{ secrets.AMPLIFY_APP_ID }}
        env-name: ${{ steps.extract.outputs.amplify-env }}

    - name: Install CI dependencies
      run: yarn install --frozen-lockfile

    - name: Install frontend dependencies
      run: yarn install --frozen-lockfile
      working-directory: frontend

    # - name: Run test
    #   run: yarn test
    #   working-directory: frontend

    - name: Build
      run: yarn build
      working-directory: frontend

    - name: Deploy
      uses: nwtgck/actions-netlify@v1.0
      with:
        publish-dir: frontend/build
        production-branch: master
        github-token: ${{ github.token }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
