name: Build & Deploy to Netlify

# https://qiita.com/nwtgck/items/e9a355c2ccb03d8e8eb0

on:
  push:
    paths:
        # frontend ディレクトリとgit直下のファイルが変更された時に実行する
        - frontend/**
        - '*'
        # Workflow/actionが変更された時も実行する
        - .github/workflows/netlify.yml
        - .github/actions/configure-amplify/**

  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install extract action dependencies
      working-directory: .github/actions/extract
      run: yarn install --frozen-lockfile

    - name: Install config-amplify action dependencies
      working-directory: .github/actions/configure-amplify
      run: yarn install --frozen-lockfile

    - name: Extract
      id: extract
      uses: ./.github/actions/extract

    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Configure Amplify using action
      uses: ./.github/actions/configure-amplify
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ap-northeast-1
        project-name: aws-amplify-handson
        app-id: ${{ secrets.AMPLIFY_APP_ID }}
        env-name: ${{ steps.extract.outputs.amplify-env }}

    - name: Install frontend dependencies
      run: yarn install --frozen-lockfile
      working-directory: frontend

    # - name: Run test
    #   run: yarn test
    #   working-directory: frontend

    - name: Build
      run: yarn build
      working-directory: frontend

    - name: Output github.token only for PR
      id: githubtoken
      run: |
        GITHUB_TOKEN=""
        if [ "${{ github.event_name }}" = "pull_request" ];then
          GITHUB_TOKEN="${{ github.token }}"
        fi
        echo "##[set-output name=tonotify]$GITHUB_TOKEN"

    - name: Deploy
      uses: nwtgck/actions-netlify@v1.0
      with:
        publish-dir: frontend/build
        production-branch: master
        github-token: ${{ steps.githubtoken.outputs.tonotify }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
